# This pipeline has no stages; instead, it exists to trigger 
# the pipeline that builds and deploys yarnspinner.dev.

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "Hello from the CI server."